### ISSUE TITLE
Deprecation warning with gtk-3.14.5

### ISSUE THREAD

**Issue by 2ion** [Unia/gcolor3#20]
```
ui.c:147:2: warning: ‘gtk_color_selection_new’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkcolorsel.h:107): Use 'gtk_color_chooser_widget_new' instead [-Wdeprecated-declarations]
  color_chooser = gtk_color_selection_new ();
```
The change seems to be non-trivial since just replacing the function call makes the 'color chooser' page in the application invisible.

**Comment by Unia** [comment]
The color selection widget has been deprecated for a few versions now. I haven't bothered updating, because the replacement does not offer a color picker like we have currently.

Thus, I'm afraid there's nothing I can do about this.
