### ISSUE TITLE
Improve the GUI

### ISSUE THREAD

**Issue by lasers** [Unia/gcolor3#22]
I'm going to see if I will want to switch to gcolor3 after using gcolor2 for long time and was comparing the features between two apps. I wanted to share my feedback. 

1) Reduce the size of gigantic textblocks? --- Red, Green, Blue and Color name
The textblocks are much bigger than the first column and that wasn't the case in gcolor2.

2) Implement the missing minus/plus buttons on Opacity textblock?
I see the slider -- but it might be easier to make it perfect "180" from 178 by pressing plus button twice than to slide it or to make the change in textblock... and to make it more constant with other buttons.

3) Rename "Color name" to "Color hex" / "Hex" ? 

O) O for optional.... Without experimenting, I can't help but ponder if it would be more intuitive to have "[#####|#####]" on first column and "Color name: [textblock] [Q]" on second column? [Q] being the colorpicker button.

**Comment by Unia** [comment]
Thank you for your feedback.

> 1) Reduce the size of gigantic textblocks? --- Red, Green, Blue and Color name
The textblocks are much bigger than the first column and that wasn't the case in gcolor2.

This is not up to me. I use the standard (although deprecated) [GtkColorSelection](https://developer.gnome.org/gtk3/stable/GtkColorSelection.html) widget. You might be able to accomplish what you want by changing and/or editing your GTK+ theme.

> 2) Implement the missing minus/plus buttons on Opacity textblock?
I see the slider -- but it might be easier to make it perfect "180" from 178 by pressing plus button twice than to slide it or to make the change in textblock... and to make it more constant with other buttons.

> 3) Rename "Color name" to "Color hex" / "Hex" ?

Again, this is not up to me for I use the standard widget.

> O) O for optional.... Without experimenting, I can't help but ponder if it would be more intuitive to have "[#####|#####]" on first column and "Color name: [textblock] [Q]" on second column? [Q] being the colorpicker button. 

I'm not sure what you mean here. Can you elaborate? In case it is the layout of what you see in the `Palette` page: everything here is the stock widget that I cannot change.

---

I guess I could extend `GtkColorSelection` ([source](https://git.gnome.org/browse/gtk+/tree/gtk/deprecated/gtkcolorsel.c)), but this would be quite a lot of work that I don't think is worth it. Perhaps in the future when it is actually removed from GTK+, but until then...

**Comment by lasers** [comment]
No problem. I thought the first three ideas would be good improvements... I'm still not sure about O idea. If it's not possible, that's okay. It puts me at ease knowing that you can't do anything about the gigantic textblocks. It was indeed odd. Many thanks for gcolor3. :)
