### ISSUE TITLE
AUR Builds Missing

### ISSUE THREAD

**Issue by breaker1** [Unia/gcolor3#26]
The AUR was just upgraded to v4 and they didn't migrate any of the old packages. Managing packages is now done through a git repository. If you don't want to go through this process, I'd be happy to re-upload your old packages. They're still available at the following locations.

http://pkgbuild.com/git/aur-mirror.git/tree/gcolor3-git
http://pkgbuild.com/git/aur-mirror.git/tree/gcolor3

**Comment by Unia** [comment]
Hello,

I am aware of the change, but have so far been unable to update my packages. I will do so soon!

**Comment by breaker1** [comment]
I recreated the aur packages. I can add you as a co-maintainer for the packages if you want to send me your username on AUR (just email the address in the PKGBUILD files)

**Comment by Unia** [comment]
Thank you for taking the time to do this. I had not come around to it yet.

Can you change my info to "Jente Hidskes <hjdskes@gmail.com>? The email adres listed in the PKGBUILD at the moment is no longer in use. Also, the gcolor3 PKGBUILD has a double entry for the md5sums :)

**Comment by breaker1** [comment]
The double entry md5sums was there in the original PKGBUILD, but I removed that line and fixed your email in both gcolor3 and gcolor3-git.
