### ISSUE TITLE
Package for Fedora

### ISSUE THREAD

**Issue by Fnux** [Unia/gcolor3#28]
Hi ! I'm building a .rpm package for Fedora and planning to add it to [Fedy](https://satya164.github.io/fedy/). Are you okay with that ?

**Comment by Unia** [comment]
Of course :) be sure to take the latest git as it solves an important issue (see the latest commit).

I plan on releasing a 2.0.1 or something soon, like this weekend - in case there is a policy or something I don't know about.

**Comment by Fnux** [comment]
I just built the 2.0 [on copr](https://copr.fedoraproject.org/coprs/fnux/GColor3/).

**Comment by Unia** [comment]
Awesome! Just some nitpicking, however:

1. Could you rename this to Gcolor3 instead of GColor3? It really is with a small c.
2. The page mentions the following:
```
The following unofficial repositories are provided as-is by owner of this project.
Contact the owner directly for bugs or issues (IE: not bugzilla).
```

Who are `the owner` and `this project`? Does it refer to you and this Copr repository, or to me and Gcolor3 as the project? Perhaps you can change the wording to make this more clear. In case `the project` is Gcolor3, could you perhaps add a link to unia.github.io/gcolor3 or the GitHub issues page?

Also, completely unrelated: I just noticed there is a second repository on Copr for Gcolor3: https://copr.fedoraproject.org/coprs/leigh123linux/gcolor3/

Can you or should I contact this person to let them know about your repository?

**Comment by Unia** [comment]
FWIW, I'll release a new stable version once I have decided whether or not to implement #30 and to apply the rewording mentioned [here](https://bbs.archlinux.org/viewtopic.php?pid=1560908#p1560908).

In fact, could I perhaps get your opinion on the rewording issue?

**Comment by Fnux** [comment]
Ok. I'm going to edit the copr page and contact the owner of the second repo today.

**Comment by leigh123linux** [comment]
Hi,

Feel free to merge my packaging improvements to your repo

https://leigh123linux.fedorapeople.org/pub/SPECS/gcolor3.spec

packaging improvements
1. install files in the proper locations (rpm should never install files in /usr/local)

https://fedoraproject.org/wiki/Packaging:Guidelines#No_Files_or_Directories_under_.2Fsrv.2C_.2Fusr.2Flocal.2C_or_.2Fhome.2F.24USER

2. Fix Source tag (must be a url)

https://fedoraproject.org/wiki/Packaging:SourceURL

3. move autogen command to %prep section and add noconfigure option, then use the %configure macro in %build section to set FLAGS and file prefixes

the %configure option =

```
$ rpm -E %configure

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro }"; export LDFLAGS; 
  [ "1" = 1 ] && for i in $(find . -name config.guess -o -name config.sub) ; do 
      [ -f /usr/lib/rpm/redhat/$(basename $i) ] && /usr/bin/rm -f $i && /usr/bin/cp -fv /usr/lib/rpm/redhat/$(basename $i) $i ; 
  done ; 
  [ "1" = 1 ] && [ x != "x" ] && 
      for i in $(find . -name ltmain.sh) ; do 
        /usr/bin/sed -i.backup -e 's~compiler_flags=$~compiler_flags=""~' $i 
      done ; 
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
	--program-prefix= \
	--disable-dependency-tracking \
	--prefix=/usr \
	--exec-prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc \
	--datadir=/usr/share \
	--includedir=/usr/include \
	--libdir=/usr/lib64 \
	--libexecdir=/usr/libexec \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info
```

4. validate the desktop file

https://fedoraproject.org/wiki/Packaging:Guidelines#desktop-file-install_usage

5. install lang files properly

https://fedoraproject.org/wiki/Packaging:Guidelines#Why_do_we_need_to_use_.25find_lang.3F

6. add scriptlet (runs gtk-update-icon-cache) so hicolor icon appears in menu without logout

https://fedoraproject.org/wiki/Packaging:ScriptletSnippets?rd=Packaging/ScriptletSnippets#Icon_Cache

7. install  AUTHORS, LICENSE and README.md using the %doc macro

https://fedoraproject.org/wiki/Packaging:Guidelines#Documentation

8. use the correct macro's in %files section

https://fedoraproject.org/wiki/Packaging:RPMMacros?rd=Packaging/RPMMacros




P.S I reserve the right to submit a formal fedora package review

https://admin.fedoraproject.org/pkgdb/packager/leigh123linux/

**Comment by Unia** [comment]
Awesome to see you guys cooperate on this :+1: Is there anything I can do on my side to assist?

A formal package review.. does that mean Gcolor3 might make its way into the official Fedora repositories? That would be great!

**Comment by Fnux** [comment]
In fact it's my first time using copr. Thank you for your help leigh. I'm going to follow your advices.

I will update the repo during the weekend.

**Comment by Unia** [comment]
I just need updated translations before I can release v2.0.1.

**Comment by Fnux** [comment]
I can provide the french translation.

**Comment by Fnux** [comment]
Just tell me what I have to translate.

**Comment by Fnux** [comment]
Oh. You already updated the english file. My bad.

**Comment by Unia** [comment]
See the README for instructions on how to translate. In this case, once you have created the `fr_new.po` file, open it and fix the last two strings marked with `fuzzy` (those two translations will still use the word `palette`) and apply the new translation for `Picker`.

**Comment by Unia** [comment]
Are you still going to do the french translation, @Fnux ? Only el, fr and sv are left before I can release a new version. I'll probably get the Swedish one done tonight.

Also, @Fnux @leigh123linux, how's everything going on the repository side?

**Comment by Fnux** [comment]
Sorry for the delay. I had a lot to do this week and wasn't able to work on gcolor3. I will provide you the french translation by tomorrow.

**Comment by Unia** [comment]
That's fine :) we all have other things to take care of, too. Looking forward to your PR!

**Comment by Fnux** [comment]
Is the new version ready ?

**Comment by Unia** [comment]
Yep!

**Comment by Unia** [comment]
Done: https://github.com/Unia/gcolor3/releases/tag/v2.1

**Comment by Fnux** [comment]
Will update the copr repo by the next week.

**Comment by Fnux** [comment]
Well, I'm not using Fedora anymore and I really don't have enough time... Can you remove the copr link from the REAME ? Sorry.

**Comment by Unia** [comment]
Can't you find someone who can take it over from you?

**Comment by Fnux** [comment]
I updated the https://copr.fedorainfracloud.org/coprs/fnux/gcolor3/ repo.

**Comment by Unia** [comment]
Thanks!

**Comment by Fnux** [comment]
Feel free to mail me if I miss a release ;)
