### ISSUE TITLE
Rename `palette` to `chooser` or `picker`

### ISSUE THREAD

**Issue by Unia** [Unia/gcolor3#31]
And perhaps rename `Saved colors` to `palette`...

**Comment by Fnux** [comment]
The actual naming is not a problem, but [this guy](https://bbs.archlinux.org/viewtopic.php?pid=1560908#p1560908) is right. I think you can change from `Palette` to `Selector`. However, I prefer `saved colors` than `Palette` for the second tab.

**Comment by Unia** [comment]
:+1: Will update everything probably later today.
