### ISSUE TITLE
Unnamed saved colours don't get out of list when deleting

### ISSUE THREAD

**Issue by palob** [Unia/gcolor3#33]
Saved colours you didnt specify names for can't be deleted from the list of saved colours.

Then again those unnamed saved colours vanish after restart anyway no matter whether or not you attempted to delete them.
So are you even supposed to be able to save colours without specifying a name?

**Comment by Unia** [comment]
I suspect you are not using the latest git version, where this should be fixed. Could you give that version a try if you indeed aren't using it?

**Comment by palob** [comment]
You're right, I wasn't using the latest git and it has been fixed meanwhile :+1:

**Comment by Unia** [comment]
Good to know :)
