### ISSUE TITLE
Allow copying saved colors to clipboard

### ISSUE THREAD

**Issue by phw** [Unia/gcolor3#43]
It would be nice if it was easy to copy saved colors easily to the clipboard, e.g. by selecting them and hitting Ctrl-C, or maybe with a context menu "copy" action.

**Comment by Unia** [comment]
Good suggestion! I'll look into this the next few days :)

**Comment by Unia** [comment]
Can you test the `copy-color` branch? Specifically commit c8daf910daccfdee9bc9a2f2492bda92e45cb28f. I think that does what you requested.

**Comment by phw** [comment]
I will test it, but only sometime next week. Please ping me should I forget ;)

**Comment by Unia** [comment]
I have reworked this feature, see b48c0118b5fb2591bd15fd1bb9f84dca27ab8849.

@phw Have you found the time to test this yet?

**Comment by phw** [comment]
Ok, tested it. Works as expected, like it very much :+1: 

From a user interface point I think there should be a way to discover this functionality, even though that's something I don't need for my usage. Maybe add a context menu with "Copy", "Rename" and "Delete"?

Another option would be to add one of those new Gtk3 keyboard shortcut help screens that show up with `Ctrl` + `?` by default. That way all of the keyboard shortcuts would be discoverable.

**Comment by Unia** [comment]
That's good to hear, I'll merge this today or tomorrow.

> From a user interface point I think there should be a way to discover this functionality...

See the `shortcuts` branch, I'm already working on bringing a `GtkShortcutsWindow` to Gcolor3 :) Also see the milestone for version 2.3.
